# 服务器配置
server:
  # 指定端口
  port: 8720
# spring 配置
spring: 
  # rabbitmq配置  
  rabbitmq:
    # rabbitmq主机地址
    host: 192.168.2.108
    # rabbitmq qmpq端口（默认5672）
    port: 5672
    # rabbitmq用户名
    username: ms_client_pro
    # rabbitmq 用户密码
    password: pro!!1234
  cloud:
    bus:
      trace:
        # 开启消息跟踪
        enable: true
        
        