# 服务器配置
server:
  # 指定该Eureka实例的端口
  port: 8710
  
# 单个eureka服务中心
spring:
  application:
    name: eureka-server
  profiles:
    active: dev
  security: 
    user: 
      name: eureka_admin
      password: eureka_admin_123  
  
# eureka服务配置
eureka:
  #instance:
    #hostname: localhost
  instance:
    prefer-ip-address: true
    # 在springcloud中服务的 Instance ID 默认值是:${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}},也就是：主机名：应用名：应用端口
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}  
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  server:
    # 关闭自我保护
    enableSelfPreservation: false  
  client:
    # 由于该应用为注册中心，所以设置为false，代表不向注册中心注册自己
    registerWithEureka: false
    # 由于注册中心的职责就是维护服务实例，他并不需要去检索服务，所以也设置为false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/



